import Head from "next/head";

import styles from "@/styles/Home.module.css";

import { Canvas } from '@react-three/fiber'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mykael Barnes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="canvas-container">
        <Canvas>
          <ambientLight intensity={0.1} />
          <directionalLight color="red" position={[0, 0, 5]} />
          <mesh>
            <boxGeometry args={[5, 5, 5]}/>
            <meshStandardMaterial />
          </mesh>
        </Canvas>
      </div>
    </>
  );
}