import Head from "next/head";

import styles from "@/styles/Home.module.css";

import { Canvas, useLoader } from '@react-three/fiber';
import { Environment, OrbitControls, Stage } from "@react-three/drei";
import { LayerMaterial, Depth } from 'lamina'
import * as THREE from 'three'

import AnimatedBox from "@/components/AnimatedBox";

export default function Home() {

  return (
    <>
      <Head>
        <title>Mykael Barnes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id={styles.canvas_container}>
        <Canvas>
          <Stage>
            <OrbitControls />
            <AnimatedBox size={[3, 3, 3]} color="blue" />
          </Stage>
        </Canvas>
      </div>
    </>
  );
}